*Update update-script

diff --git a/stable/update-script b/stable/update-script
--- a/stable/update-script
+++ b/stable/update-script
@@ -1,12 +1,20 @@
 #!/bin/sh
 if [[ -f "/tmp/BackOn/Update/info/runUpdateODS" ]]; then
 	runUpdateODS="$(cat "/tmp/BackOn/Update/info/runUpdateODS")"
+else
+	if [[ -f "/var/mobile/Library/Preferences/BackOn/runUpdateODS" ]]; then
+		runUpdateODS="$(cat "/tmp/BackOn/Update/info/runUpdateODS")"
+	else
+		runUpdateODS=NO
+	fi
 fi
 if [[ -f "/tmp/BackOn/Update/info/UpdateBuildType" ]]; then
 	UpdateBuildType="$(cat "/tmp/BackOn/Update/info/UpdateBuildType")"
 fi
 if [[ -f "/tmp/BackOn/Update/info/updateWithDEBInstall" ]]; then
 	updateWithDEBInstall="$(cat "/tmp/BackOn/Update/info/updateWithDEBInstall")"
+else
+	updateWithDEBInstall=YES
 fi
 if [[ -f "/tmp/BackOn/Update/info/UpdaterVersion" ]]; then
 	UpdaterVersion="$(cat "/tmp/BackOn/Update/info/UpdaterVersion")"
@@ -15,37 +23,48 @@ else
 fi
 if [[ -f "/tmp/BackOn/Update/info/showLog" ]]; then
 	showLog="$(cat "/tmp/BackOn/Update/info/showLog")"
+else
+	showLog=NO
+fi
+if [[ -f "/tmp/BackOn/Update/info/applyColorScheme" ]]; then
+	applyColorScheme="$(cat "/tmp/BackOn/Update/info/applyColorScheme")"
+else
+	applyColorScheme=YES
 fi
 if [[ -f "/tmp/BackOn/Update/info/UpdateBuildVersion" ]]; then
 	UpdateBuildVersion="$(cat "/tmp/BackOn/Update/info/UpdateBuildVersion")"
 fi
 
 function Update1(){
-	echo "UpdaterVersion : 1"
-	cp backon.sh /usr/bin/backon
-	chmod +x /usr/bin/backon
-	if [[ -f /var/mobile/Library/Preferences/BackOn/runUpdateODS ]]; then
-		if [[ "$(cat "/var/mobile/Library/Preferences/BackOn/runUpdateODS")" == YES ]]; then
-			backon -ods; exit 0
-		fi
+	UpdateBuildType="${PWD##*/}"
+	UpdateBuildVersion="$(cat build)"
+	showInfo
+	if [[ "${UpdateBuildType}" == alpha ]]; then
+		cp backon.sh /usr/bin/backon
+		chmod +x /usr/bin/backon
+	elif [[ "${UpdateBuildType}" == beta || "${UpdateBuildType}" == stable ]]; then
+		killCydia
+		applyPurple
+		dpkg -i "../deb-${UpdateBuildType}/${UpdateBuildType}-${UpdateBuildVersion}.deb"
+		applyNoColor
+	else
+		applyRed
+		echo "ERROR!"
+		applyNoColor
+		exit 1
 	fi
-	backon; exit 0
+	runBackOn
 }
 
 function Update2(){
 	if [[ "${showLog}" == YES ]]; then
-		echo "UpdaterVersion : 2"
-		echo "runUpdateODS : ${runUpdateODS}"
-		echo "UpdateBuildType : ${UpdateBuildType}"
-		echo "updateWithDEBInstall : ${updateWithDEBInstall}"
-		echo "UpdaterVersion : ${UpdaterVersion}"
-		echo "showLog : ${showLog}"
-		echo "UpdateBuildVersion : ${UpdateBuildVersion}"
-		showPressAnyKeyToContinue
+		showInfo
 	fi
 	if [[ "${updateWithDEBInstall}" == YES && ! "${UpdateBuildType}" == alpha ]]; then
 		if [[ "${showLog}" == YES ]]; then
+			applyPurple
 			dpkg -i "/tmp/BackOn/Update/master/BackOn-master/deb-${UpdateBuildType}/${UpdateBuildType}-${UpdateBuildVersion}.deb"
+			applyNoColor
 		else
 			dpkg -i "/tmp/BackOn/Update/master/BackOn-master/deb-${UpdateBuildType}/${UpdateBuildType}-${UpdateBuildVersion}.deb" > /dev/null 2>&1
 		fi
@@ -56,8 +75,69 @@ function Update2(){
 	runBackOn
 }
 
+function showInfo(){
+	applyPurple
+	echo -e "UpdaterVersion : ${UpdaterVersion}"
+	echo -e "runUpdateODS : ${runUpdateODS}"
+	echo -e "UpdateBuildType : ${UpdateBuildType}"
+	echo -e "updateWithDEBInstall : ${updateWithDEBInstall}"
+	echo -e "showLog : ${showLog}"
+	echo -e "applyColorScheme : ${applyColorScheme}"
+	echo -e "UpdateBuildVersion : ${UpdateBuildVersion}"
+	applyNoColor
+	showPressAnyKeyToContinue
+}
+
+function applyRed(){
+	if [[ "${applyColorScheme}" == YES ]]; then
+		echo -e -n "\033[0;31m"
+	fi
+}
+
+function applyPurple(){
+	if [[ "${applyColorScheme}" == YES ]]; then
+		echo -e -n "\033[1;35m"
+	fi
+}
+
+function applyLightCyan(){
+	if [[ "${applyColorScheme}" == YES ]]; then
+		echo -e -n "\033[1;36m"
+	fi
+}
+
+function applyNoColor(){
+	if [[ "${applyColorScheme}" == YES ]]; then
+		echo -e -n "\033[0m"
+	fi
+}
+
 function showPressAnyKeyToContinue(){
+	applyLightCyan
 	read -s -n 1 -p "Press Any key to continue..."
+	applyNoColor
+	echo -e
+}
+
+function killCydia(){
+	ps cax | grep Cydia > /dev/null
+	if [ $? -eq 0 ]; then
+		if [[ "${showLog}" == YES ]]; then
+			applyPurple
+			echo -e "Killing Cydia..."
+			applyNoColor
+		fi
+		killall -9 Cydia
+	fi
+	ps cax | grep MobileCydia > /dev/null
+	if [ $? -eq 0 ]; then
+		if [[ "${showLog}" == YES ]]; then
+			applyPurple
+			echo -e "Killing MobileCydia..."
+			applyNoColor
+		fi
+		killall -9 MobileCydia
+	fi
 }
 
 function runBackOn(){
@@ -76,6 +156,8 @@ if [[ "${UpdaterVersion}" == 1 ]]; then
 elif [[ "${UpdaterVersion=}" == 2 ]]; then
 	Update2
 else
+	applyRed
 	echo "ERROR!"
+	applyNoColor
 	exit 1
 fi
