*Update beta/update-script

diff --git a/beta/update-script b/beta/update-script
--- a/beta/update-script
+++ b/beta/update-script
@@ -1,12 +1,16 @@
 #!/bin/sh
 if [[ -f "/tmp/BackOn/Update/info/runUpdateODS" ]]; then
 	runUpdateODS="$(cat "/tmp/BackOn/Update/info/runUpdateODS")"
+else
+	runUpdateODS=NO
 fi
 if [[ -f "/tmp/BackOn/Update/info/UpdateBuildType" ]]; then
 	UpdateBuildType="$(cat "/tmp/BackOn/Update/info/UpdateBuildType")"
 fi
 if [[ -f "/tmp/BackOn/Update/info/updateWithDEBInstall" ]]; then
 	updateWithDEBInstall="$(cat "/tmp/BackOn/Update/info/updateWithDEBInstall")"
+else
+	updateWithDEBInstall=YES
 fi
 if [[ -f "/tmp/BackOn/Update/info/UpdaterVersion" ]]; then
 	UpdaterVersion="$(cat "/tmp/BackOn/Update/info/UpdaterVersion")"
@@ -15,21 +19,36 @@ else
 fi
 if [[ -f "/tmp/BackOn/Update/info/showLog" ]]; then
 	showLog="$(cat "/tmp/BackOn/Update/info/showLog")"
+else
+	showLog=NO
 fi
 if [[ -f "/tmp/BackOn/Update/info/applyColorScheme" ]]; then
 	applyColorScheme="$(cat "/tmp/BackOn/Update/info/applyColorScheme")"
+else
+	applyColorScheme=YES
 fi
 if [[ -f "/tmp/BackOn/Update/info/UpdateBuildVersion" ]]; then
 	UpdateBuildVersion="$(cat "/tmp/BackOn/Update/info/UpdateBuildVersion")"
 fi
 
 function Update1(){
-	applyPurple
-	echo "UpdaterVersion : 1"
-	applyNoColor
-	showPressAnyKeyToContinue
-	cp backon.sh /usr/bin/backon
-	chmod +x /usr/bin/backon
+	UpdateBuildType="${PWD##*/}"
+	UpdateBuildVersion="$(cat build)"
+	showInfo
+	if [[ "${UpdateBuildType}" == alpha ]]; then
+		cp backon.sh /usr/bin/backon
+		chmod +x /usr/bin/backon
+	elif [[ "${UpdateBuildType}" == beta || "${UpdateBuildType}" == stable ]]; then
+		killCydia
+		applyPurple
+		dpkg -i "$../deb-${UpdateBuildType}/${UpdateBuildType}-${UpdateBuildVersion}.deb"
+		applyNoColor
+	else
+		applyRed
+		echo "ERROR!"
+		applyNoColor
+		exit 1
+	fi
 	if [[ -f /var/mobile/Library/Preferences/BackOn/runUpdateODS ]]; then
 		if [[ "$(cat "/var/mobile/Library/Preferences/BackOn/runUpdateODS")" == YES ]]; then
 			backon -ods; exit 0
@@ -40,16 +59,7 @@ function Update1(){
 
 function Update2(){
 	if [[ "${showLog}" == YES ]]; then
-		applyPurple
-		echo -e "UpdaterVersion : 2"
-		echo -e "runUpdateODS : ${runUpdateODS}"
-		echo -e "UpdateBuildType : ${UpdateBuildType}"
-		echo -e "updateWithDEBInstall : ${updateWithDEBInstall}"
-		echo -e "showLog : ${showLog}"
-		echo -e "applyColorScheme : ${applyColorScheme}"
-		echo -e "UpdateBuildVersion : ${UpdateBuildVersion}"
-		applyNoColor
-		showPressAnyKeyToContinue
+		showInfo
 	fi
 	if [[ "${updateWithDEBInstall}" == YES && ! "${UpdateBuildType}" == alpha ]]; then
 		if [[ "${showLog}" == YES ]]; then
@@ -64,6 +74,19 @@ function Update2(){
 		chmod +x /usr/bin/backon
 	fi
 	runBackOn
+}
+
+function showInfo(){
+	applyPurple
+	echo -e "UpdaterVersion : ${UpdaterVersion}"
+	echo -e "runUpdateODS : ${runUpdateODS}"
+	echo -e "UpdateBuildType : ${UpdateBuildType}"
+	echo -e "updateWithDEBInstall : ${updateWithDEBInstall}"
+	echo -e "showLog : ${showLog}"
+	echo -e "applyColorScheme : ${applyColorScheme}"
+	echo -e "UpdateBuildVersion : ${UpdateBuildVersion}"
+	applyNoColor
+	showPressAnyKeyToContinue
 }
 
 function applyRed(){
@@ -95,6 +118,27 @@ function showPressAnyKeyToContinue(){
 	read -s -n 1 -p "Press Any key to continue..."
 	applyNoColor
 	echo -e
+}
+
+function killCydia(){
+	ps cax | grep Cydia > /dev/null
+	if [ $? -eq 0 ]; then
+		if [[ "${showLog}" == YES ]]; then
+			applyPurple
+			echo -e "Killing Cydia..."
+			applyNoColor
+		fi
+		killall -9 Cydia
+	fi
+	ps cax | grep MobileCydia > /dev/null
+	if [ $? -eq 0 ]; then
+		if [[ "${showLog}" == YES ]]; then
+			applyPurple
+			echo -e "Killing MobileCydia..."
+			applyNoColor
+		fi
+		killall -9 MobileCydia
+	fi
 }
 
 function runBackOn(){
