*alpha-172

diff --git a/alpha/update-script b/alpha/update-script
--- a/alpha/update-script
+++ b/alpha/update-script
@@ -24,12 +24,28 @@ if [[ -f "/tmp/BackOn/Update/info/UpdateBuildVersion" ]]; then
 fi
 
 function Update1(){
+	UpdateBuildType="${PWD##*/}"
+	UpdateBuildVersion="${cat build}"
 	applyPurple
 	echo "UpdaterVersion : 1"
+	echo "UpdateBuildType : ${UpdateBuildType}"
+	echo "UpdateBuildVersion : ${UpdateBuildVersion}"
 	applyNoColor
 	showPressAnyKeyToContinue
-	cp backon.sh /usr/bin/backon
-	chmod +x /usr/bin/backon
+	if [[ "${UpdateBuildType}" == alpha ]]; then
+		cp backon.sh /usr/bin/backon
+		chmod +x /usr/bin/backon
+	elif [[ "${UpdateBuildType}" == beta || "${UpdateBuildType}" == stable ]]; then
+		killCydia
+		applyPurple
+		dpkg -i "${../deb-${UpdateBuildType}/${UpdateBuildType}-${UpdateBuildVersion}.deb"
+		applyNoColor
+	else
+		applyRed
+		echo "ERROR!"
+		applyNoColor
+		exit 1
+	fi
 	if [[ -f /var/mobile/Library/Preferences/BackOn/runUpdateODS ]]; then
 		if [[ "$(cat "/var/mobile/Library/Preferences/BackOn/runUpdateODS")" == YES ]]; then
 			backon -ods; exit 0
@@ -95,6 +111,27 @@ function showPressAnyKeyToContinue(){
 	read -s -n 1 -p "Press Any key to continue..."
 	applyNoColor
 	echo -e
+}
+
+function killCydia(){
+	ps cax | grep Cydia > /dev/null
+	if [ $? -eq 0 ]; then
+		if [[ "${showLog}" == YES ]]; then
+			applyPurple
+			echo -e "Killing Cydia..."
+			applyNoColor
+		fi
+		killall -9 Cydia
+	fi
+	ps cax | grep MobileCydia > /dev/null
+	if [ $? -eq 0 ]; then
+		if [[ "${showLog}" == YES ]]; then
+			applyPurple
+			echo -e "Killing MobileCydia..."
+			applyNoColor
+		fi
+		killall -9 MobileCydia
+	fi
 }
 
 function runBackOn(){
